//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen3_Rec
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devoluciones
    {
        public int id_devolucion { get; set; }
        public string fechaDevolucion { get; set; }
        public Nullable<int> id_alumno { get; set; }
        public Nullable<int> id_libro { get; set; }
    
        public virtual Alumnos Alumnos { get; set; }
        public virtual Libros Libros { get; set; }
    }
}
